### ISSUE TITLE
Docker Volume

### ISSUE THREAD

**Issue by SebStaeubert** [Dockerizing/OntoWiki#2]
Hi,

you use 'Volume' in the Dockerfile
https://github.com/Dockerizing/OntoWiki/blob/master/Dockerfile
https://github.com/Dockerizing/OntoWiki/commit/175f8ebce79fd034674baa8f52abbde9d4037a95

If one has to modify something in /var/www/html , e.g. in docker-compose or an other Dockerfile which uses the ontowiki container, this would have no effect because the VOLUME "seals" this directory!
It is better to define the Volume in docker-compose.yml
```
  ontowiki:
    build: ./ontowiki
    volumes:
      - /var/www/html
    links:
      - virtuoso
```

Regards,
Sebastian
